# Generated by Django 4.1.7 on 2023-03-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skmsapp', '0002_remove_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userimage',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile/'),
        ),
    ]
