# Generated by Django 4.1.6 on 2023-03-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skmsapp', '0006_comment_post_comment_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportReplyToSubmitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitter', models.CharField(max_length=50, null=True)),
                ('report_reply', models.TextField()),
                ('reply_date', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.TextField()),
            ],
        ),
    ]
