# Generated by Django 4.1.6 on 2023-03-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skmsapp', '0007_reportreplytosubmitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportreplytosubmitter',
            name='is_read',
            field=models.CharField(max_length=1),
        ),
    ]
