# Generated by Django 4.1.6 on 2023-03-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skmsapp', '0008_alter_reportreplytosubmitter_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportreplytosubmitter',
            name='activity_date',
            field=models.DateField(null=True),
        ),
    ]
