# Generated by Django 4.1.6 on 2023-03-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skmsapp', '0009_reportreplytosubmitter_activity_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportreplytosubmitter',
            name='activity_date',
            field=models.DateTimeField(null=True),
        ),
    ]
