# Generated by Django 4.1.6 on 2023-03-06 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skmsapp', '0010_alter_reportreplytosubmitter_activity_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='report',
            name='contact_preference',
            field=models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], default='Y', max_length=3),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_anonymously',
            field=models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], default='N', max_length=3),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporter_name',
            field=models.CharField(choices=[('Current User', 'Current User'), ('Anonymous', 'Anonymous')], default='Current User', max_length=300),
        ),
        migrations.AlterField(
            model_name='voice',
            name='contact_preference',
            field=models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], default='Y', max_length=3),
        ),
        migrations.AlterField(
            model_name='voice',
            name='voice_anonymously',
            field=models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], default='N', max_length=3),
        ),
        migrations.AlterField(
            model_name='voice',
            name='voice_user',
            field=models.CharField(choices=[('Current User', 'Current User'), ('Anonymous', 'Anonymous')], default='Current User', max_length=300),
        ),
    ]
