# Generated by Django 4.1.6 on 2023-03-06 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skmsapp', '0011_alter_comment_author_alter_post_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subject',
            field=models.CharField(choices=[('Asset', 'Asset'), ('Counter Measure', 'Counter Measure'), ('Threat', 'Threat'), ('Vulnerability', 'Vulnerability')], max_length=100),
        ),
    ]
