# Generated by Django 4.1.6 on 2023-03-06 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skmsapp', '0013_alter_post_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('assetid', models.AutoField(db_column='AssetID', primary_key=True, serialize=False)),
                ('assetname', models.TextField(db_column='AssetName', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Countermeasures',
            fields=[
                ('countermeasureid', models.AutoField(db_column='CounterMeasureID', primary_key=True, serialize=False)),
                ('countermeasurename', models.TextField(db_column='CounterMeasureName', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Threats',
            fields=[
                ('threatid', models.AutoField(db_column='ThreatID', primary_key=True, serialize=False)),
                ('threatname', models.TextField(db_column='ThreatName', unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(related_name='post_comments', to='skmsapp.comment'),
        ),
        migrations.CreateModel(
            name='CountermeasureDescriptions',
            fields=[
                ('countermeasureid', models.OneToOneField(db_column='CounterMeasureID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='skmsapp.countermeasures')),
                ('countermeasuredescription', models.TextField(db_column='CounterMeasureDescription')),
            ],
        ),
        migrations.CreateModel(
            name='ThreatDescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threatdescription', models.TextField(db_column='ThreatDescription')),
                ('threatid', models.OneToOneField(db_column='ThreatID', on_delete=django.db.models.deletion.DO_NOTHING, to='skmsapp.threats')),
            ],
        ),
    ]
