# Generated by Django 4.1.6 on 2023-03-06 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skmsapp', '0015_rename_assets_asset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('assetid', models.AutoField(db_column='AssetID', primary_key=True, serialize=False)),
                ('assetname', models.TextField(db_column='AssetName', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Countermeasures',
            fields=[
                ('countermeasureid', models.AutoField(db_column='CounterMeasureID', primary_key=True, serialize=False)),
                ('countermeasurename', models.TextField(db_column='CounterMeasureName', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThreatDescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threatdescription', models.TextField(db_column='ThreatDescription')),
            ],
        ),
        migrations.CreateModel(
            name='Threats',
            fields=[
                ('threatid', models.AutoField(db_column='ThreatID', primary_key=True, serialize=False)),
                ('threatname', models.TextField(db_column='ThreatName', unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.RemoveField(
            model_name='countermeasuredescription',
            name='countermeasureid',
        ),
        migrations.RemoveField(
            model_name='threatdescription',
            name='threatid',
        ),
        migrations.CreateModel(
            name='CountermeasureDescriptions',
            fields=[
                ('countermeasureid', models.OneToOneField(db_column='CounterMeasureID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='skmsapp.countermeasures')),
                ('countermeasuredescription', models.TextField(db_column='CounterMeasureDescription')),
            ],
        ),
        migrations.DeleteModel(
            name='Countermeasure',
        ),
        migrations.DeleteModel(
            name='CountermeasureDescription',
        ),
        migrations.DeleteModel(
            name='Threat',
        ),
        migrations.DeleteModel(
            name='ThreatDescription',
        ),
        migrations.AddField(
            model_name='threatdescriptions',
            name='threatid',
            field=models.OneToOneField(db_column='ThreatID', on_delete=django.db.models.deletion.DO_NOTHING, to='skmsapp.threats'),
        ),
    ]
