# Generated by Django 4.1.6 on 2023-03-06 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skmsapp', '0016_assets_countermeasures_threatdescriptions_threats_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assets',
        ),
        migrations.RemoveField(
            model_name='threatdescriptions',
            name='threatid',
        ),
        migrations.DeleteModel(
            name='CountermeasureDescriptions',
        ),
        migrations.DeleteModel(
            name='Countermeasures',
        ),
        migrations.DeleteModel(
            name='ThreatDescriptions',
        ),
        migrations.DeleteModel(
            name='Threats',
        ),
    ]
