# Generated by Django 4.1.6 on 2023-03-06 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skmsapp', '0017_delete_assets_remove_threatdescriptions_threatid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('assetid', models.AutoField(db_column='AssetID', primary_key=True, serialize=False)),
                ('assetname', models.TextField(db_column='AssetName', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Countermeasure',
            fields=[
                ('countermeasureid', models.AutoField(db_column='CounterMeasureID', primary_key=True, serialize=False)),
                ('countermeasurename', models.TextField(db_column='CounterMeasureName', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Threat',
            fields=[
                ('threatid', models.AutoField(db_column='ThreatID', primary_key=True, serialize=False)),
                ('threatname', models.TextField(db_column='ThreatName', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CountermeasureDescription',
            fields=[
                ('countermeasureid', models.OneToOneField(db_column='CounterMeasureID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='skmsapp.countermeasure')),
                ('countermeasuredescription', models.TextField(db_column='CounterMeasureDescription')),
            ],
        ),
        migrations.CreateModel(
            name='ThreatDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threatdescription', models.TextField(db_column='ThreatDescription')),
                ('threatid', models.OneToOneField(db_column='ThreatID', on_delete=django.db.models.deletion.DO_NOTHING, to='skmsapp.threat')),
            ],
        ),
    ]
