# Generated by Django 4.1.6 on 2023-03-06 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skmsapp', '0018_asset_countermeasure_threat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
