# Generated by Django 4.1.6 on 2023-03-29 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skmsapp', '0014_category_alter_post_comments_securityterm'),
        ('skmsapp', '0021_vulnerability'),
    ]

    operations = [
    ]
